### ISSUE TITLE
Optimize Ansible scripts by removing repeatable tasks

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/ansible-is#10]
**Description:**

Ansible scripts for Identity Server use repeatable task to copy every single configuration file as below. 
```- name: "Copy master-datasource.xml"
      template:
        src: "carbon-home/repository/conf/datasources/master-datasources.xml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/datasources/master-datasources.xml"

    - name: "Copy identity.xml"
      template:
        src: "carbon-home/repository/conf/identity/identity.xml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/identity/identity.xml"

    - name: "Copy carbon.xml"
      template:
        src: "carbon-home/repository/conf/carbon.xml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/carbon.xml"

    - name: "Copy registry.xml"
      template:
        src: "carbon-home/repository/conf/registry.xml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/registry.xml"

    - name: "Copy axis2.xml"
      template:
        src: "carbon-home/repository/conf/axis2/axis2.xml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/axis2/axis2.xml"
```

But there is a optimal way to achieve same as follows:

TASKS:
```
- name: copy wso2 conf files
  template:
    src:   "{{ carbon_home }}/repository/conf/{{ item.source }}"
    dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/repository/conf/{{ item.dest }}"
    owner: "{{ wso2_user }}"
    group: "{{ wso2_group }}"
  with_items: "{{ config_files }}"
```

VARS:
```
config_files:

  - source: 'datasources/master-datasources.xml.j2'
    dest: 'datasources/master-datasources.xml'

  - source: 'identity/identity.xml.j2'
    dest: 'identity/identity.xml'

  - source: 'carbon.xml.j2'
    dest: 'carbon.xml'

  - source: 'registry.xml.j2'
    dest: 'registry.xml'

  - source: 'axis2/axis2.xml.j2'
    dest: 'axis2/axis2.xml' 
```

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@VimukthiPerera 

**Affected Product Version:**
v5.7.0.1
