### ISSUE TITLE
Error while executing role for the first time: "Could not find the requested service

### ISSUE THREAD

**Issue by Savidude** [wso2/ansible-is#24]
**Description:**
Needs to be fixed by moving the 

```
- name: Copy WSO2IS service file
   template:
     src: "wso2is.service.j2"
     dest: /etc/systemd/system/wso2is.service
```

Block to before the server is being stopped at 
```
- name: Stop wso2is as a service
   systemd:
     name: wso2is
     state: stopped
```

**Suggested Labels:**
Type/Bug
Priority/High

**Suggested Assignees:**
@Savidude
