### ISSUE TITLE
JDK unzipping failure 

### ISSUE THREAD

**Issue by Savidude** [wso2/ansible-is#40]
**Description:**
Sometimes the JDK archive name is different from the extracted folder name. Current Ansible scripts expect them to be the same.

**Suggested Labels:**
Type/Bug
Priority/Normal

**Suggested Assignees:**
@chirangaalwis

**Comment by VimukthiPerera** [comment]
**Possible Fix**
```
- name: Unzip JDK
  unarchive:
    src: /path/to/jdk.tar.gz
    dest: /path/to/extract/{{ jdk_name }}
    extra_opts: [--strip-components=1]
```
